# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10fe10f565277673cdcca54b22ada780bb2116dff96d80e9d19639958e2706f95dc4818f8823366098502a71c915743a41d894b3df42865b0f9183319707436e

test:
  secret_key_base: e268a549df43b4c598221cec1255e6daa595b2603118bbf67a21960e1c83ad0de6223f7579b8420f91d274d44ce8e34d4693e5c768bc166eccdd94f874bc23fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
